image:
  - Visual Studio 2017

platform:
  - x64

install:
  - cmd: call C:\\Miniconda36-x64\Scripts\activate.bat
  - cmd: conda.exe config --add channels conda-forge
  - cmd: conda.exe config --set show_channel_urls true
  - cmd: appveyor-retry conda.exe install --yes --quiet "conda!=4.6.1" conda-forge-pinning conda-forge-ci-setup=2.* networkx conda-build>=3.16
  - cmd: conda.exe list

build: off
